use_frameworks!

platform :ios, '12.4'

target 'ICD10Kit_Example' do
  pod 'ICD10Kit', :path => '../'
  pod 'RealmSwift', '~> 10.43'
  pod 'SwiftLint'

  target 'ICD10Kit_Tests' do
    inherit! :search_paths

    
  end
end
